# Change these first
owner: PanchoSavEnergy # Your GitHub organization or username, where this repository lives
repo: MonitoreoPaginasWeb # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: SavEnergy SpA
    url: https://www.savenergyspa.com/
  - name: SavEnergy Instagram
    url: https://www.instagram.com/savenergy.spa/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: API Rest Favoritos Url
    url: https://shorturl-session.herokuapp.com/auth/login
    
    

assignees:
  - PanchoSavEnergy

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /MonitoreoPaginasWeb
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoreo de páginas externas 
  introTitle: "Bienvenido al proyecto **Upptime**. Herramienta de código abierto, y hosteado en GitHub Pages."
  introMessage: "Esta es una página de monitoreo que verifica el status de otras páginas para verificar si éstas se encuentran online. Utiliza datos en **tiempo real** desde el [repositorio Github original](https://github.com/upptime/upptime). No necesita un servidor externo para funcionar — sólo las herramientas de GitHub: Actions, Issues, and Pages. [**¿Quieres aprender a usar esta herramienta?**](https://github.com/upptime/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
